### ISSUE TITLE
Measure number of initial installations

### ISSUE THREAD

**Issue by openjck** [mdn/discord#100]

**Comment by openjck** [comment]
We could use the `ping` event to track this.

**Comment by openjck** [comment]
This will probably be the first feature that needs a database. I'm torn between SQLite and PostgreSQL. What do you think @groovecoder?

**Comment by groovecoder** [comment]
Postgres. :muscle:

**Comment by openjck** [comment]
Awesome! Heroku [strongly agrees](https://devcenter.heroku.com/articles/sqlite3).

> Heroku provides production grade PostgreSQL databases as a service.
> Why is SQLite a bad fit for running on Heroku?
> Instead of using SQLite on Heroku you can configure your app to run on Postgres.

:open_mouth:

**Comment by openjck** [comment]
PR #147 adds code for logging pings. After that lands, we'll want to create a `metrics` table and update it whenever a new ping is recorded. The table might look something like this:

```
id: integer
name: string
description: text
value: integer
```

Sequelize has a handy [`afterUpdate`](https://sequelize.readthedocs.org/en/latest/api/hooks/#afterupdatename-fn) hook that we might want to use as part of this.

**Comment by openjck** [comment]
Hm, apparently starting a commit message with *Issue #NNN* closes the corresponding issue. Anyway, there's still more work to do on this (see [this comment](https://github.com/mdn/discord/issues/100#issuecomment-129574152)). In the meantime, we can get this metric a little more manually by running a query. We just don't want to have to do that for every metric we collect.

**Comment by groovecoder** [comment]
@openjck and I agreed we can call this done since we're able to get this measurement via psql.

**Comment by openjck** [comment]
Yep! And we can open new issues in the future if/when we want metrics to be summarized in a different table or dashboard.
