### ISSUE TITLE
UI crash

### ISSUE THREAD

**Issue by EagleEYErus** [mdn/discord#177]
The application UI crashes. I was faced with this problem and in VSCode.

<img src="https://user-images.githubusercontent.com/15634499/31282292-cf71ec92-aaba-11e7-8c7f-410ce9dcde08.png">

**Comment by openjck** [comment]
Different Discord. Please report your problem to the [Discord chat app](https://discordapp.com/) team instead.

**Comment by openjck** [comment]
@groovecoder I don't have permissions to close this, but it's ready to be closed.

**Comment by EagleEYErus** [comment]
@openjck Is it possible to remove the issue ticket?

**Comment by openjck** [comment]
Unfortunately it's not possible to completely remove an issue. Only close it.

See this [GitHub feature request for completely removing issues](https://github.com/isaacs/github/issues/253).
