### ISSUE TITLE
Add compatibility comments to pull requests

### ISSUE THREAD

**Issue by groovecoder** [mdn/Discord#28]
**Current specification**

When someone submits a pull request to a repository that has YouShouldUse installed, it should go through and add compatibility comments to the lines of code modified in the pull request.

![An open pull request with two inline compatibility comments](https://cloud.githubusercontent.com/assets/933396/7969874/eb3e2e1e-0a07-11e5-816b-cd087b1b825a.png)

**Comment by darkwing** [comment]
I setup the tools as documented and, using this commit:

https://github.com/darkwing/compat-tables/commit/d5891f64ec34e1a4df4b1d017fc8d2d9a3268fb0

... I'm seeing no change in result:

http://content.screencast.com/users/davidwalsh83/folders/Jing/media/69be5eb8-3b4a-4ac7-a311-3281ca9127d8/00000291.png

**Comment by groovecoder** [comment]
I wonder if this only happens on *new* CSS files? What happens if you make an edit to the file? Does it kick in then?

**Comment by darkwing** [comment]
I added a subsequent commit and no notifications:

https://github.com/darkwing/compat-tables/commit/6a68c00554d7018884ed5f3ad69dbe374708351e

I did see this error in my logs:

https://gist.github.com/darkwing/07c62033ebec91928228

**Comment by openjck** [comment]
Let's talk about that issue in IRC. Pull request commenting hasn't been implemented yet.

**Comment by openjck** [comment]
Updated description with current specification.

**Comment by mrmakeit** [comment]
currently, PR support requires additional configuration of the webhook on the repository side.  By default it only sends Push messages, so you have to manually add Pull_Request to the given messages.

**Comment by mrmakeit** [comment]
@darkwing Do you have a GitHub token in the OAUTH_TOKEN env variable?  Without it, the comment request fail and don't return the right values.

**Comment by mrmakeit** [comment]
some potential issues:
1. when creating a PR from a branch on the same repository, the webhook will receive both a `pull_request` event, and a `push` event.  The order of these events is unknown, so we would have to deal with race conditions.
2. when creating a PR from a branch on a remote repository, we would not receive notices when the branch is updated.

Any thoughts?

**Comment by mrmakeit** [comment]
ah, correction on 2,
  we would receive `update` events as well, but this would be for both PR updates (comments, title change, etc) and branch changes.  So, how should we differentiate.  I don't think we get a manifest of what has changes.  (researching now to double check)

**Comment by mrmakeit** [comment]
As for remote branch PR's, it looks like the best way to handle them is to use the PR Review Comment.  I have a commit almost ready for it.

**Comment by darkwing** [comment]
Here's what I've done that is *not* yet working:

1.  Go to my GitHub settings, created a Personal Access Token with the permissions:  admin:org_hook, admin:repo_hook, gist, repo, user

2.  Added token to my env:  export OAUTH_TOKEN=XXXXXX

3.  Added a commit to my test repo's master branch, pushed to GitHub

4.  Checked out the commit display on GitHub...no comments :(

**Comment by openjck** [comment]
@groovecoder: Did you say you wanted to check with Legal about whether this is allowed by the GitHub Terms of Service?

**Comment by mrmakeit** [comment]
Review Comments apply to the merge commit, which is located on the local repo, not the head repo. That should keep us from affecting repos we dont have access to.

**Comment by openjck** [comment]
Does the merge commit exist before it's merged?

**Comment by mrmakeit** [comment]
Surprisingly, yes.

**Comment by mrmakeit** [comment]
unless it is unarguable.

**Comment by openjck** [comment]
Interesting. Sure, whatever allows the comments to appear like in the image above.

It would be great to also have the comments appear when the commit is non-mergeable. From the user's point of view, the code is either compatible or incompatible regardless of the conflict status.

**Comment by mrmakeit** [comment]
unfortunately, line comments either come from the merge commit, or from the head repo.  If it isn't mergable, there wont be a commit to comment on.

**Comment by openjck** [comment]
Gotcha. We may be able to comment to the head repo. Luke's going to look into that with Legal.

**Comment by openjck** [comment]
You mentioned that commenting in other repositories might be against the Terms of Service. Do you remember where you saw that? We could use that as a starting point when looking into it with Legal.

**Comment by mrmakeit** [comment]
It's been a while since I ran into that.  Let me see if I wrote it down anywhere.

**Comment by openjck** [comment]
In our meeting this morning, Luke and I talked about just doing this now and handling fallout (if any) later. I think we have a strong case for the value of automatic commenting.

**Comment by openjck** [comment]
Hey Blixa! :smile:

My schedule is pretty open for the next couple of weeks. I'm trying to decide between working on this and working on a Kuma feature ([bug 1139490](https://bugzilla.mozilla.org/show_bug.cgi?id=1139490)). Does this interest you? If so, I can get out of your way. If not, I can do this now and the Kuma thing later. Either way really.

It might be fun to demo this at the Whistler meetup (June 22<sup>nd</sup> to June 26<sup>th</sup>) if we get it done in time.

**Comment by mrmakeit** [comment]
I'm actually out of town on a camping trip this weekend, so feel free to
jump on it.

On Thu, Jun 11, 2015, 09:44 John Karahalis <notifications@github.com> wrote:

> Hey Blixa! [image: :smile:]
>
> My schedule is pretty open for the next couple of weeks. I'm trying to
> decide between working on this and working on a Kuma feature (bug 1139490
> <https://bugzilla.mozilla.org/show_bug.cgi?id=1139490>). Does this
> interest you? If so, I can get out of your way. If not, I can do this now
> and the Kuma thing later. Either way really.
>
> It might be fun to demo this at the Whistler meetup (June 22nd to June 26
> th) if we get it done in time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdn/YouShouldUse/issues/28#issuecomment-111158443>.
>
-- 

-------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by openjck** [comment]
Have fun!

I can start today. I probably won't get far before Monday, but can plan to keep working on it until Whislter. Feel free to hop in if you feel interested at any point. :smile:

**Comment by openjck** [comment]
As part of this change, I'm going to disable commit commenting. Many other services like this (like Code Climate, Jenkins, and Travis) work at the pull request level. Sticking with that [convention](http://goodui.org/#29) will make the tool more predictable and will also simplify the codebase.
