### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by groovecoder** [mdn/discord#51]
We're getting to the point where we want tests on the repo so we can test against certain payloads without having to make real commits on GitHub.

**Comment by mrmakeit** [comment]
for end-to-end testing, I've been working on a small project to test GitHub webhooks without GitHub interaction.  Since all the webhooks use the URL variables, I've been substituting those for the test server, allowing collection of the results.

**Comment by openjck** [comment]
@groovecoder: Did you say you tested GitHub webhooks on another project?

**Comment by groovecoder** [comment]
Not webhooks; I used some simple Mocha, Chai, and nock to test some other node code:

https://github.com/codefortulsa/water-in-the-river/blob/master/test/gaugeSpec.js

**Comment by darkwing** [comment]
For reference;  http://putaindecode.fr/posts/ci/webhooks-github/

**Comment by openjck** [comment]
Done!

https://github.com/mdn/discord/tree/master/tests
