### ISSUE TITLE
Invalid Comment Count

### ISSUE THREAD

**Issue by darkwing** [mdn/discord#53]
At present, when a commit's files are analyzed by YSU, the *entire* file is analyzed instead of simply the file's diff data.  This is problematic because the repo page shows one comment count for the commit:

https://camo.githubusercontent.com/97b8401bdc0161d88b275b74b952f64a5913bbea/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f646176696477616c736838332f666f6c646572732f4a696e672f6d656469612f35346563636539632d313336322d343063622d383137322d3464363837383334316665612f30303030303239382e706e67

...instead of just the number of comments that the use will be shown when the browse the commit itself.

**Comment by darkwing** [comment]
This succeeds https://github.com/mdn/YouShouldUse/issues/50

**Comment by mrmakeit** [comment]
the entire file is analyzed due to how doiuse works.  The file2diff function will automatically ignore any lines not added in the diff.  Since github only accepts comments on diff lines, there is no way to add a comment that is not in the diff.

**Comment by groovecoder** [comment]
Is this still an issue? I haven't noticed it in a while ...

**Comment by openjck** [comment]
It looks like GitHub no longer shows the comment mentioned in the description. My guess is that it was a bug on their end anyway.

**Comment by openjck** [comment]
In fact, this issue refers to commit comments, which we no longer publish. We publish pull request comments instead. So regardless of what caused the bug, it's not something we have to worry about any more.
