### ISSUE TITLE
Update doiuse dependency

### ISSUE THREAD

**Issue by groovecoder** [mdn/Discord#57]
We're using `doiuse` 0.3.3 released May 2. The latest is 1.0.2 release today.

**Comment by mrmakeit** [comment]
The ^ should cause it to use the latest version.  A simple redeploy should update it.

**Comment by mrmakeit** [comment]
I will bump the doiuse version to pin it.

**Comment by mrmakeit** [comment]
So #58 should for it to 1.0.2.  @mrmakeit: not to self, 0. versions do not auto upgrade to 1. versions.
