### ISSUE TITLE
Contribution instruction: token creation instructions unclear

### ISSUE THREAD

**Issue by federicoculloca** [mdn/discord#66]
Today, while setting up the environment, I noticed the instructions about the creation of a personal access token inside the CONTRIBUTING.md file are unclear. It seems one should add the following permissions:

- admin:repo_hook
- admin:org_hook

Or so I've been instructed by @darkwing .

Is this correct? If yes, I'll amend the file to include the information.

**Comment by mrmakeit** [comment]
this is not correct.  The token only requires the user permission.  admin:*_hook is for adding hooks to the users repos, which the tool does not do.

**Comment by openjck** [comment]
Sounds like this can be closed then?
