### ISSUE TITLE
Post a discussion comment when a stylesheet cannot be tested

### ISSUE THREAD

**Issue by openjck** [mdn/discord#67]
There may be times when a stylesheet cannot be tested: for example, if Stylus cannot be compiled. When this happens, we should post a comment to the pull request discussion (not a line comment) mentioning that the stylesheet could not be tested.

**Comment by darkwing** [comment]
Do we add a comment to the top or bottom line of each errant file committed instead?  Just something to consider.  Or do we add the one discussion comment with a listing of errant files?

**Comment by mrmakeit** [comment]
The discussion comments would probably be the best place.

**Comment by groovecoder** [comment]
:+1: for one discussion comment.

**Comment by openjck** [comment]
Good question. There's really no standard way to comment on a file.

A common workaround is to comment on the first or last line. One downside with that approach is that it overloads the purpose of line-comments&mdash;for example, it emails a diff of the nearby lines to the commit author and stick around until that specific line is changed. I'm not sure those line-comment behaviors would make sense here.

**Comment by openjck** [comment]
This could be noisy until #49 is fixed, and may or may not be needed once it is. I do want to keep thinking about this even if we don't have enough information to commit to it right now. Let's say not now and circle back down the road.
