### ISSUE TITLE
Add New Relic

### ISSUE THREAD

**Issue by groovecoder** [mdn/discord#73]
New Relic provides some great preformance and error monitoring. It's very easy to add to Heroku apps.

https://devcenter.heroku.com/articles/newrelic
https://devcenter.heroku.com/articles/newrelic#node-js-installation-and-configuration

**Comment by openjck** [comment]
:+1:

**Comment by openjck** [comment]
@darkwing Would we say this is done?

**Comment by mrmakeit** [comment]
New relic has been installed for a while now.
