### ISSUE TITLE
Track views to the Discord homepage

### ISSUE THREAD

**Issue by openjck** [mdn/discord#99]

**Comment by openjck** [comment]
Maybe GA integration?

**Comment by groovecoder** [comment]
Yeah, that's what I propose.

**Comment by groovecoder** [comment]
Why MVP #2 and not #1?

**Comment by openjck** [comment]
We can definitely try to squeeze it in for MVP 1. Who would be able to generate a tracking code for us?

**Comment by openjck** [comment]
Yeah, this should have been in MVP 1 all along. That's where we decided to put the metric-related features. Shouldn't take long.

**Comment by groovecoder** [comment]
Gareth Cull should be able to give us a new property in the "Mozilla (small websites)" account.
